AWSTemplateFormatVersion: '2010-09-09'
Description: Sample SAM Template for Hello World
Globals:
  Function:
    Timeout: 3
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: ApiGatewayAPI
        - .execute-api.
        - Ref: AWS::Region
        - .amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
Resources:
  ApiGatewayAPI:
    Properties:
      DefinitionUri: s3://milkgate-serverless-deployments/hello-world/00806ccb5fa6a8b6ace0e106d20a6bc2
      StageName: Prod
    Type: AWS::Serverless::Api
  HelloWorldFunction:
    Properties:
      CodeUri: s3://milkgate-serverless-deployments/hello-world/b8a244f3af6528dc83374665f2b84a3c
      Environment:
        Variables:
          PARAM1: VALUE
      FunctionName: hello-world-sam-2
      Handler: app.lambdaHandler
      Role: arn:aws:iam::438594535251:role/serverless-deployment-service-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
