AWSTemplateFormatVersion: '2010-09-09'
Description: Sample SAM Template for Hello World
Globals:
  Function:
    Timeout: 3
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: ApiGatewayAPI
        - .execute-api.
        - Ref: AWS::Region
        - .amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
Resources:
  ApiGatewayAPI:
    Properties:
      DefinitionUri: s3://serverless-sam-hello-world/126c8ae01d0b858088edfa3bc7514883
      StageName: Prod
    Type: AWS::Serverless::Api
  HelloWorldFunction:
    Properties:
      CodeUri: s3://serverless-sam-hello-world/acc465ba6bd175de3e7b8e5e1f49035c
      Environment:
        Variables:
          PARAM1: VALUE
      FunctionName: hello-world-sam-owan
      Handler: app.lambdaHandler
      Role: arn:aws:iam::275552291381:role/DevLambdaRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
