openapi: '3.0.1'
info:
    title: 'hello-world-sam'
    version: '1.0'
servers:
    - url: 'https://nkfbvalxg7.execute-api.us-east-1.amazonaws.com/{basePath}'
      variables:
          basePath:
              default: '/Prod'
paths:
    /hello:
        get:
            x-amazon-apigateway-integration:
                credentials: 'arn:aws:iam::438594535251:role/serverless-deployment-service-role'
                uri: 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:438594535251:function:hello-world-sam-owan/invocations'
                passthroughBehavior: 'when_no_match'
                httpMethod: 'POST'
                contentHandling: 'CONVERT_TO_TEXT'
                type: 'aws_proxy'
components: {}
